### ISSUE TITLE
charts пропадают из index.md

### ISSUE THREAD

**Issue by GusevVictor** [EvgenyVenalainen/jd-folders-tool#1]
Евгений, добрый день! Огромная благодарность за софт! Крутейший!

Подскажите, почему такое происходит: стоит добавить какой-либо файл - exe и др. в things - сразу же исчезает раздел tiny chart в index.md?  Я так понимаю, Вы только картинки подсчитываете? - Если немного поясните для новичков, буду весьма рад. Спасибо. Одно бы дело другие расширения игнорировались, а тут именно вообще всё пропадет. Хоть бы размеры видеть, уже было бы классно в чарте. А то всё прямо слетает

**Comment by EvgenyVenalainen** [comment]
Приветствую! Здорово, что пригодилась программа!
Нет, должны все файлы плюсоваться в общую сумму, у меня и exe тоже считает. В принципе, исходный файл программы - Johnny.Decimal.ahk - лежит в корневой папке репозитория, можно установить AutoHotkey и потестировать, посмотреть, что происходит. А как вы запускаете прогамму - Johnny.Decimal.exe из Release 1.0.0 или из корневой папки репозитория? У меня текущая версия уже далеко от релиза 1.0 ушла, надо бы обновить. Пришлите мне тестовый пример, где не рабоатает - структуру папок с несколькими файлами внутри архивом, можно на эл. почту на @mozmail.com - которая в профайле, попробую у себя запустить.

**Comment by GusevVictor** [comment]
Из корневой папки репозитария: 1.1.37.2 версия. Снова постараюсь воспроизвести, сейчас не смотря на наличие файла exe стала появляться статистика, в папке sample которую я Вам приготовил на отправку. 

Сейчас буду активно пользоваться, как только выловлю снова проблему, сразу положу на Яндекс диск архив. 

Огромное спасибо за быстрый отзыв! Очень круто. Программа, меняет жизнь прямо, как и сама система именования!

**Comment by GusevVictor** [comment]
И так, как будто бы я разобрался как ловить проблему:

Как воспроизвести:

1. Загрузить пример отсюда, распаковать https://disk.yandex.ru/d/CpM4Oie3FYNq3w
2. Удалить файл index.md
3. Запустить: Johnny.Decimal.exe
4. Увидим в файле index.md, блоки чарта, и блок медиа. Если процедуру повторить, останется иногда вот так только блок чарт, иногда будет вообще пусто, см. вложение. Ума не приложу почему так. Win 11

[index.md](https://github.com/user-attachments/files/18214285/index.md)

**Comment by EvgenyVenalainen** [comment]
Кажется, я знаю почему так, тоже бывало - надо закрыть Obsidian (или хотябы закрыть этот vault) перед запуском Johnny.Decimal.exe, иначе Обсидиан временами запрещает писать в открытый index.md.

**Comment by GusevVictor** [comment]
Решено. Действительно. Не очевидно, конечно. Огромное спасибо! Нижайший поклон. Закрыл Obsidian, и файл стал всегда размеров в 5кб. И всё что нужно есть.
