### ISSUE TITLE
Не корректно отображается размер в obsidian

### ISSUE THREAD

**Issue by GusevVictor** [EvgenyVenalainen/jd-folders-tool#2]
Евгений, добрый день! Если не затруднит, могли бы подсказать, почему присутствуют символ пробела, вместо самого пробела? С примером из репозитария, аналогично. Obsidian v 1.7.7

Тестовый пример: https://disk.yandex.ru/d/CpM4Oie3FYNq3w

![image](https://github.com/user-attachments/assets/c4c4fddd-77a1-4e32-a710-28225f7d293c)

**Comment by EvgenyVenalainen** [comment]
Приветствую, Виктор!
Уже могу не вспомнить, но кажется это из-за особенности синтаксиса AutoHotkey версии 1 , он полупроцедурный - полуфункциональный, и удобнее строковое выражение составить с &nbsp, чем с одним символом пробела, его интерпретатор проигнорирует.
Вот здесь, например:
`FileAppend, ![](<%path2%/%A_LoopFileName%>)&nbsp;, %index%`
И, кроме того, &nbsp не хуже и очень кстати - не даёт перенос сделать, а единицы измерений не должны отрываться от числа.
А в режиме просмотра уже всё будет с пробелами.

Или именно в режиме редактирования желательно видеть настоящие приобелы? Это совсем не трудно поменять или добавить возможность.

**Comment by GusevVictor** [comment]
Добрый день!

> А в режиме просмотра уже всё будет с пробелами.

Огромная благодарность. Я первый раз вижу Obsidian, по этому, ещё не всё усвоил. Спасибо за то, что подсказали, про режим просмотра. Увидел кнопку, перевел в режим просмотра. Проблема, действительно ушла!


![image](https://github.com/user-attachments/assets/0d057f5a-74b8-43f0-9653-4eece8ecab23)


Низкий поклон и здоровья Вам!
